<?php

/**
 * Implements hook_leaflet_map_info_alter().
 */
function leaflet_zoomfs_leaflet_map_info_alter(&$maps) {
  foreach ($maps as &$map) {
    if (isset($map['plugins']['zoomfs'])) {
      // Disable default zoom control.
      $map['settings']['zoomControl'] = FALSE;
    }
  }
}

/**
 *  Implements hook_preprocess_HOOK().
 */
function leaflet_zoomfs_preprocess_leaflet_map(&$variables) {
  if (isset($variables['map']['plugins']['zoomfs'])) {
    $variables['#attached']['library'][] = 'leaflet_zoomfs/drupal';
  }
}
